#!/usr/bin/env python3
"""Build the right-arm-only 13-DOF grasp asset and reference scene.

The zarm_r1 fixed parent frame becomes world origin.  The table, support and
handle are translated by the inverse of the former complete-robot arm-base
pose, so all arm-to-task relative poses remain unchanged.
"""

from __future__ import annotations

import copy
import json
import math
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

# This module initializes Isaac Sim and provides the shared source constants,
# object/environment builders and USD helpers.
import build_stage0_scene as stage0

from isaacsim.asset.importer.mjcf import MJCFImporter, MJCFImporterConfig
from pxr import Gf, PhysxSchema, Sdf, Usd, UsdGeom, UsdLux, UsdPhysics


ARM_XML = ROOT / "assets/robots/kuavo_s63_right_arm_dexhand_rl.xml"
ARM_OUTPUT_DIR = ROOT / "assets/robots/generated"
ARM_SCENE_USD = ROOT / "scenes/kuavo_grasp_arm_only.usd"
ARM_NOMINAL_JSON = ROOT / "config/arm_only_nominal.json"

ARM_BASE_COMPLETE = stage0.ARM_BASE_POSITION
ORIGIN = (0.0, 0.0, 0.0)


def translated(position):
    return tuple(float(position[i] - ARM_BASE_COMPLETE[i]) for i in range(3))


TABLE_CENTER = translated(stage0.TABLE_CENTER)
SUPPORT_CENTER = translated(stage0.SUPPORT_CENTER)
TABLE_TOP_Z = stage0.TABLE_TOP_Z - ARM_BASE_COMPLETE[2]
SUPPORT_TOP_Z = stage0.SUPPORT_TOP_Z - ARM_BASE_COMPLETE[2]
GROUND_Z = -ARM_BASE_COMPLETE[2]
OBJECT_SPAWN_POSITION = translated(
    (stage0.OBJECT_XY[0], stage0.OBJECT_XY[1], stage0.OBJECT_SPAWN_Z)
)
OBJECT_SPAWN_ORIENTATION_WXYZ = (
    0.9490681886672974,
    -0.29321109794890343,
    -0.07567815365522251,
    0.08700369163840316,
)
OBJECT_GRASP_POSITION = (
    0.6105805039405823,
    0.2528553903102875,
    -0.16413183510303497,
)
OBJECT_GRASP_ORIENTATION_WXYZ = (
    0.9519889950752258,
    -0.2871457951370857,
    -0.046092119340648254,
    0.09560210314339268,
)
PALM_POSITION = translated(stage0.PALM_POSITION)


def create_arm_only_mjcf() -> None:
    """Extract zarm_r1 and descendants; discard every unrelated body/mesh."""
    stage0.create_robot_mjcf()
    source_root = ET.parse(stage0.ROBOT_XML).getroot()
    source_arm = next(
        (body for body in source_root.iter("body") if body.get("name") == "zarm_r1_link"),
        None,
    )
    if source_arm is None:
        raise RuntimeError("The derived complete robot has no zarm_r1_link subtree")

    arm = copy.deepcopy(source_arm)
    arm.set("pos", "0 0 0")
    joint_names = [joint.get("name") for joint in arm.iter("joint")]
    if len(joint_names) != 13 or set(joint_names) != set(stage0.ACTIVE_JOINTS):
        raise RuntimeError(f"Arm-only subtree has unexpected joints: {joint_names}")

    used_meshes = {
        geom.get("mesh") for geom in arm.iter("geom") if geom.get("mesh")
    }
    source_assets = source_root.find("asset")
    if source_assets is None:
        raise RuntimeError("The source robot has no asset block")

    root = ET.Element("mujoco", model="kuavo_s63_right_arm_dexhand_rl")
    for tag in ("compiler", "size"):
        element = source_root.find(tag)
        if element is not None:
            root.append(copy.deepcopy(element))
    assets = ET.SubElement(root, "asset")
    for mesh in source_assets.findall("mesh"):
        if mesh.get("name") in used_meshes:
            assets.append(copy.deepcopy(mesh))
    if {mesh.get("name") for mesh in assets.findall("mesh")} != used_meshes:
        raise RuntimeError("Not every mesh used by the arm subtree was found in <asset>")

    worldbody = ET.SubElement(root, "worldbody")
    # The importer removes a joint authored directly on the top-level body
    # when fix_base=True.  This geometry-free fixed parent keeps zarm_r1_joint
    # as a real articulation DOF while still placing its parent frame at origin.
    fixed_base = ET.SubElement(worldbody, "body", name="arm_base", pos="0 0 0")
    ET.SubElement(
        fixed_base,
        "inertial",
        pos="0 0 0",
        mass="0.001",
        diaginertia="0.000001 0.000001 0.000001",
    )
    fixed_base.append(arm)
    for tag in ("actuator", "sensor"):
        element = source_root.find(tag)
        if element is not None:
            root.append(copy.deepcopy(element))

    body_names = [body.get("name") for body in root.iter("body")]
    forbidden = ("base_link", "torso", "waist_yaw_link", "zarm_l1_link")
    if any(name in body_names for name in forbidden):
        raise RuntimeError(f"Complete-robot body leaked into arm-only asset: {body_names}")

    ET.indent(root, space="  ")
    header = (
        "<?xml version='1.0' encoding='utf-8'?>\n"
        "<!-- Generated by scripts/build_arm_only_scene.py; zarm_r1 base is origin. -->\n"
    )
    ARM_XML.write_text(
        header + ET.tostring(root, encoding="unicode") + "\n", encoding="utf-8"
    )


def find_or_import_arm_usd() -> Path:
    existing = sorted(
        ARM_OUTPUT_DIR.glob(
            "kuavo_s63_right_arm_dexhand_rl*/kuavo_s63_right_arm_dexhand_rl.usda"
        )
    )
    if existing:
        return existing[0].resolve()
    config = MJCFImporterConfig(
        mjcf_path=str(ARM_XML.resolve()),
        usd_path=str(ARM_OUTPUT_DIR.resolve()),
        import_scene=False,
        merge_mesh=False,
        collision_from_visuals=False,
        collision_type="Convex Hull",
        allow_self_collision=False,
        robot_type="Manipulator",
        fix_base=True,
        run_asset_transformer=True,
        run_multi_physics_conversion=True,
    )
    result = Path(MJCFImporter(config).import_mjcf()).resolve()
    if not result.is_file():
        raise RuntimeError(f"MJCF importer did not create {result}")
    return result


def relative_asset_path(asset: Path) -> str:
    return Path(os.path.relpath(asset, ARM_SCENE_USD.parent)).as_posix()


def create_arm_scene(robot_usd: Path, half_extents) -> None:
    stage = Usd.Stage.CreateNew(str(ARM_SCENE_USD))
    UsdGeom.SetStageMetersPerUnit(stage, 1.0)
    UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.z)
    stage.SetTimeCodesPerSecond(120.0)
    stage.SetStartTimeCode(0.0)
    stage.SetEndTimeCode(1_000_000.0)
    world = UsdGeom.Xform.Define(stage, "/World")
    stage.SetDefaultPrim(world.GetPrim())

    environment = UsdGeom.Xform.Define(stage, "/World/Environment")
    environment.GetPrim().GetReferences().AddReference(
        relative_asset_path(stage0.ENVIRONMENT_USD)
    )
    environment.AddTranslateOp().Set(Gf.Vec3d(*(-x for x in ARM_BASE_COMPLETE)))
    environment.GetPrim().CreateAttribute(
        "stage0:tableTop", Sdf.ValueTypeNames.Double, custom=True
    ).Set(TABLE_TOP_Z)
    environment.GetPrim().CreateAttribute(
        "stage0:supportTop", Sdf.ValueTypeNames.Double, custom=True
    ).Set(SUPPORT_TOP_Z)

    robot = UsdGeom.Xform.Define(stage, "/World/Robot")
    robot.GetPrim().GetReferences().AddReference(relative_asset_path(robot_usd))
    robot.AddTranslateOp().Set(Gf.Vec3d(*ORIGIN))
    arm_base = UsdGeom.Xform.Define(stage, "/World/Robot/ArmBaseReference")
    arm_base.GetPrim().CreateAttribute(
        "stage0:description", Sdf.ValueTypeNames.String, custom=True
    ).Set("Arm-only root frame; identical to the fixed parent frame of zarm_r1_joint")

    handle = UsdGeom.Xform.Define(stage, "/World/OuterHandle")
    handle.GetPrim().GetReferences().AddReference(relative_asset_path(stage0.OBJECT_USD))
    handle.AddTranslateOp().Set(Gf.Vec3d(*OBJECT_SPAWN_POSITION))
    handle.AddOrientOp().Set(
        Gf.Quatf(
            OBJECT_SPAWN_ORIENTATION_WXYZ[0],
            Gf.Vec3f(*OBJECT_SPAWN_ORIENTATION_WXYZ[1:]),
        )
    )

    physics = UsdPhysics.Scene.Define(stage, "/World/PhysicsScene")
    physics.CreateGravityDirectionAttr().Set(Gf.Vec3f(0.0, 0.0, -1.0))
    physics.CreateGravityMagnitudeAttr().Set(9.81)
    physx_scene = PhysxSchema.PhysxSceneAPI.Apply(physics.GetPrim())
    physx_scene.CreateEnableCCDAttr().Set(True)
    physx_scene.CreateTimeStepsPerSecondAttr().Set(120)

    dome = UsdLux.DomeLight.Define(stage, "/World/EnvironmentLight")
    dome.CreateColorAttr().Set(Gf.Vec3f(0.72, 0.78, 0.90))
    dome.CreateIntensityAttr().Set(850.0)
    dome.CreateExposureAttr().Set(0.5)
    dome.GetPrim().CreateAttribute(
        "visibleInPrimaryRay", Sdf.ValueTypeNames.Bool, custom=True
    ).Set(True)
    light = UsdLux.DistantLight.Define(stage, "/World/KeyLight")
    light.CreateColorAttr().Set(Gf.Vec3f(1.0, 0.93, 0.82))
    light.CreateIntensityAttr().Set(2200.0)
    light.CreateAngleAttr().Set(2.0)
    light.AddRotateXYZOp().Set(Gf.Vec3f(-42.0, 28.0, 24.0))

    target_q = dict(zip(stage0.ACTIVE_JOINTS, stage0.ARM_Q + stage0.HAND_Q))
    gains = dict(
        zip(
            stage0.ACTIVE_JOINTS,
            zip(stage0.ARM_KP + stage0.HAND_KP, stage0.ARM_KD + stage0.HAND_KD),
        )
    )
    revolute = []
    driven = set()
    for prim in stage.Traverse():
        if not prim.IsA(UsdPhysics.RevoluteJoint):
            continue
        name = prim.GetName()
        revolute.append(name)
        if name not in target_q:
            continue
        drive = UsdPhysics.DriveAPI.Apply(prim, "angular")
        drive.CreateTypeAttr().Set("force")
        drive.CreateStiffnessAttr().Set(gains[name][0])
        drive.CreateDampingAttr().Set(gains[name][1])
        drive.CreateTargetPositionAttr().Set(math.degrees(target_q[name]))
        state = PhysxSchema.JointStateAPI.Apply(prim, "angular")
        state.CreatePositionAttr().Set(math.degrees(target_q[name]))
        state.CreateVelocityAttr().Set(0.0)
        driven.add(name)
    if set(revolute) != set(stage0.ACTIVE_JOINTS) or driven != set(stage0.ACTIVE_JOINTS):
        raise RuntimeError(f"Arm-only imported joint mismatch: {revolute}")

    robot.GetPrim().CreateAttribute(
        "stage0:activeJointNames", Sdf.ValueTypeNames.StringArray, custom=True
    ).Set(list(stage0.ACTIVE_JOINTS))
    robot.GetPrim().CreateAttribute(
        "stage0:assetScope", Sdf.ValueTypeNames.String, custom=True
    ).Set("right arm and right dexterous hand only; complete robot body removed")
    world.GetPrim().CreateAttribute(
        "stage0:scope", Sdf.ValueTypeNames.String, custom=True
    ).Set("arm-only asset/physics baseline; no PPO or Isaac Lab task")
    stage.GetRootLayer().Save()

    nominal = {
        "schema_version": 1,
        "units": {"length": "m", "angle": "rad", "quaternion": "wxyz"},
        "coordinate_convention": {
            "world_origin": "fixed parent frame of zarm_r1_joint",
            "world_orientation": "same axes as the former complete-robot world frame",
            "transform_from_complete_scene": {
                "translation": [-value for value in ARM_BASE_COMPLETE],
                "rotation_wxyz": [1.0, 0.0, 0.0, 0.0],
            },
        },
        "asset_scope": "right arm + right three-finger dexterous hand only",
        "removed_complete_robot_body": True,
        "active_joint_names": list(stage0.ACTIVE_JOINTS),
        "robot_root_world_pose": {"position": list(ORIGIN), "orientation": [1, 0, 0, 0]},
        "right_arm_base_world_pose": {"position": list(ORIGIN), "orientation": [1, 0, 0, 0]},
        "table": {
            "center_position": list(TABLE_CENTER),
            "orientation": [1, 0, 0, 0],
            "size": list(stage0.TABLE_SIZE),
            "top_z": TABLE_TOP_Z,
        },
        "temporary_support": {
            "center_position": list(SUPPORT_CENTER),
            "orientation": [1, 0, 0, 0],
            "size": list(stage0.SUPPORT_SIZE),
            "top_z": SUPPORT_TOP_Z,
        },
        "ground_z": GROUND_Z,
        "object_spawn_world_pose": {
            "position": list(OBJECT_SPAWN_POSITION),
            "orientation": list(OBJECT_SPAWN_ORIENTATION_WXYZ),
            "free_fall_gap": stage0.DROP_HEIGHT,
        },
        "object_nominal_settled_world_pose": {
            "position": list(OBJECT_GRASP_POSITION),
            "orientation": list(OBJECT_GRASP_ORIENTATION_WXYZ),
            "note": "Latest user-adjusted settled pose, expressed in arm-base coordinates.",
        },
        "arm_base_to_object_nominal": {
            "position": list(OBJECT_GRASP_POSITION),
            "orientation": list(OBJECT_GRASP_ORIENTATION_WXYZ),
        },
        "right_palm_initial_world_pose": {
            "position": list(PALM_POSITION),
            "orientation": list(stage0.PALM_ORIENTATION_WXYZ),
            "approach_axis_toward_object": list(stage0.PALM_APPROACH_AXIS),
        },
        "arm_base_to_right_palm": {
            "position": list(PALM_POSITION),
            "orientation": list(stage0.PALM_ORIENTATION_WXYZ),
        },
        "right_arm_initial_joint_positions": dict(zip(stage0.ARM_JOINTS, stage0.ARM_Q)),
        "right_hand_initial_joint_positions": dict(zip(stage0.HAND_JOINTS, stage0.HAND_Q)),
        "right_hand_joint_limits_rad": {
            name: list(stage0.HAND_JOINT_LIMITS[name]) for name in stage0.HAND_JOINTS
        },
        "object": {
            "half_extents": [float(value) for value in half_extents],
            "mass": stage0.OBJECT_MASS,
            "collision": "convexDecomposition",
        },
    }
    ARM_NOMINAL_JSON.write_text(
        json.dumps(nominal, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    stage0.ensure_directories()
    ARM_XML.parent.mkdir(parents=True, exist_ok=True)
    ARM_SCENE_USD.parent.mkdir(parents=True, exist_ok=True)
    ARM_NOMINAL_JSON.parent.mkdir(parents=True, exist_ok=True)
    create_arm_only_mjcf()
    robot_usd = find_or_import_arm_usd()
    half_extents = stage0.create_object_asset()
    stage0.create_environment_asset()
    create_arm_scene(robot_usd, half_extents)
    print(f"ARM_ONLY_MJCF={ARM_XML}")
    print(f"ARM_ONLY_ROBOT_USD={robot_usd}")
    print(f"ARM_ONLY_SCENE_USD={ARM_SCENE_USD}")
    print(f"ARM_ONLY_NOMINAL_JSON={ARM_NOMINAL_JSON}")
    print("ACTIVE_DOF_COUNT=13")
    print("REMOVED_COMPLETE_ROBOT_BODY=true")
    print("BUILD_RESULT=PASS")
    return 0


if __name__ == "__main__":
    exit_code = 1
    try:
        exit_code = main()
    except Exception:
        import traceback

        traceback.print_exc()
    finally:
        stage0.simulation_app.close(exit_code=exit_code)
    raise SystemExit(exit_code)
